### ISSUE TITLE
How to run on GPU with cuda 11.3 or 11.2

### ISSUE THREAD

**Issue by gexahedron** [threedle/text2mesh#2]
Hi! Do you know, maybe, how to run the code on GPU with CUDA 11.3 or 11.2? AFAIU, one would need pytorch 1.10 for this, but then kaolin asks for pytorch <= 1.9

**Comment by factoryofthesun** [comment]
Hi sorry for the delayed response. Like you said Kaolin requires pytorch <= 1.9, so unfortunately I don't believe it is possible to run kaolin, and thus the code, with CUDA > 11.1.
