### ISSUE TITLE
Two Intro Questions

### ISSUE THREAD

**Issue by metaphorz** [threedle/text2mesh#6]
I did not see a Discussion section, so asking here in Issues: (1) Has anyone published a Google Colab notebook? and (2) how was the animation created of the vase?

For (1), I can whip one up assuming that the CUDA matches what Colab gives. Otherwise, this needs tweaking

For (2), it looks like you are varying the seed and/or the text prompt and then perhaps creating keyframes which are then interpolated? It is a cool effect. The other would be to explore 3D printing of things like "the cactus shoe"

**Comment by roibaron** [comment]
Hi @metaphorz,

1. We hope to publish one soon, I'll let you know when it happens.
2. We morphed different styles created by applying various text prompts on the same content mesh. See Fig. 9 in the paper.
